# Bem-vindo {.unnumbered}

## Visão Geral da Iniciativa Countdown to 2030 {.unnumbered}

A iniciativa Countdown to 2030 para a Saúde da Mulher, da Criança e do Adolescente (The Countdown) é uma colaboração global que envolve académicos de instituições nacionais, regionais e internacionais, agências da ONU, o Banco Mundial e organizações da sociedade civil. A iniciativa acompanha o progresso na Saúde e Nutrição Reprodutiva, Materna, Neonatal, Infantil e do Adolescente (RMNCAH+N), promovendo a advocacia e a responsabilização através de uma análise rigorosa de dados.

**Os principais objetivos incluem:**

-   Fortalecer a análise e o monitoramento de dados liderados pelos países
-   Promover a inovação e a geração de evidências através da colaboração multinacional
-   Aprimorar a medição e o monitoramento global
-   Melhorar a comunicação de políticas e programas

Para mais informações sobre a iniciativa Countdown to 2030, visite: [O site The Countdown](https://www.countdown2030.org/about)

## Sobre o pacote R `cd2030.extractor` {.unnumbered}

O aplicativo Shiny `cd2030.extractor` foi desenvolvido para facilitar o download de dados do Countdown diretamente a partir do DHIS2.  
É compatível com instâncias do DHIS2 em todos os países suportados.

O código-fonte está disponível no GitHub:  
[https://github.com/aphrcwaro/extractor_guide](https://github.com/aphrcwaro/extractor_guide)

A documentação completa está disponível em:  
[https://aphrcwaro.github.io/extractor_guide/](https://aphrcwaro.github.io/extractor_guide/)

### Principais funcionalidades

- Interface intuitiva para seleção e gerenciamento de dados  
- Exportação dos dados no formato padrão do Countdown, pronto para análise e geração de relatórios

