# App Features

## Overview of App Features

This section details the main components of the **cd2030.extractor** Shiny App interface: the **Top Navigation Bar (Green Header)**, **Sidebar (Data Controls)**, and **Main Panel (Body Content)**. Understanding these elements will help you navigate and use the app more effectively.

## Navigation Bar (Top Menu)

The Top Navigation Bar, located at the top of the app, provides key controls. The navigation tabs included `Service Data`, `Population Data` and `Countdown Data`. On the right side it contains the name of the logged in user and the country

### Key Elements of the Top Navigation Bar

1.  **Service Data Tab**: This is mean to download the data for.

images

2.  **Population Data Tab**

3.  **Countdown Tab**

4.  **Context Information**

    -   

## Sidebar

The Sidebar is located on the left side of the app and contains the main navigation elements.It provides navigation through the analysis workflow. The sections are arranged sequentially to guide you through the process.

### Sidebar Navigation

images

1.  **Introduction**: Provides a brief overview of the app's purpose and functionality.

2.  **Load Data**: Allows you to upload and manage your datasets (e.g. Health Facility Datasets, Master datasets, and cache file).

3.  **Data Quality**: Provides tools for assessing the quality of your data, including checks for missing values and inconsistencies. Subsections include:

    -   Reporting Rate
    -   Outlier Detection
    -   Consistency Check
    -   Data Completeness
    -   Calculate Ratios
    -   Overall Score

images

4.  **Analysis Set-up**: Allows you to configure the analysis by selecting the data sources (UN Estimates, WUENIC estimates, and survey data). It also allows you to map the sub-national survey and mapping data to the uploaded data.

images

5.  **National Analysis**: Provides tools for analyzing national-level data, including coverage and equity analysis.
6.  **Sub-National Analysis:** For all sub-national analyses
7.  **Mortality Analysis:** For all mortality analyses
8.  **Service Utilization:** ForCurative health services utilization for sick children analyses
9.  **Health System Performance:** Health systems progress and performance analysis

## Main Panel(Body Content)

The main panel is the central workspace where the analysis result, visualizations, and interactive elements are displayed.

### Key Elements of the Main Panel

1.  **Page Title**: Displays the current module or analysis step (e.g., "Reporting Rate").

images

2.  **Action Buttons**: Provides context-specific actions:
    -   **Download Report**: Helps you to download two reports: **Synthesis report** and the **Subnational one paper report**

    -   **Generate Report**: Downloads a report specific to the analysis section.

        NB: This button is green in colour and only appears in the sections where the user can download the section reports.

    -   **Get Help**: Provides context-specific help and documentation for the current page.

    -   **Download Plot / Download Data:** Allows the user to download the displayed output and the data associated with the output, respectively.
